philharmonic_foyer_service:
    resource: "@PhilharmonicFoyerServiceBundle/Resources/config/routing.yml"
    prefix:   /

BackendBundle:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /

UserBundle:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /