user_login:
    path:     /login
    defaults: { _controller: UserBundle:Default:login }

user_check:
    path:  /user_check

user_logout:
    path:     /
    defaults: { _controller: UserBundle:Default:logout }