user_login:
    path:     /login
    defaults: { _controller: UserBundle:Default:login }

user_check:
    path:     /user_check

redirect_to_user_login:
    path:     /
    defaults:
        _controller:  FrameworkBundle:Redirect:redirect
        route:        user_login
        permanent:    true

user_profile:
    path:     /in/user

user_edit:
    path:     /in/user/edit