user_login:
    path:     /
    defaults: { _controller: UserBundle:Default:login }

user_check:
    path:  /user_check

user_logout:
    path:     /logout
    defaults: { _controller: UserBundle:Default:logout }

user_in:
    path:     /in
    defaults: { _controller: UserBundle:Default:index }