user_login:
    path:     /login
    defaults: { _controller: UserBundle:Default:login }

user_check:
    path:     /user_check

redirect_to_user_login:
    path:     /
    defaults:
        _controller:  FrameworkBundle:Redirect:redirect
        route:        user_login
        permanent:    true

user_profile:
    path:     /in/userprofile

user_edit_user:
    path:     /in/user/edit

user_edit_profile:
    path:     /in/profile/edit
    defaults: { _controller: UserBundle:Profile:edit }