security:
    encoders:
        cmh\UserBundle\Entity\User:
            algorithm:        sha512
            encode_as_base64: true

    access_decision_manager:
        strategy: unanimous

    providers:
        administrators:
            entity: { class: UserBundle:User }

    firewalls:
        admin_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  user_login
                check_path:  user_check
                default_target_path: /in
            access_denied_handler: security.access_denied.handler
            logout:
                path:   /logout
                target: /login
                invalidate_session: true
                delete_cookies:
                    a: { path: null, domain: null }
                    b: { path: null, domain: null }

    access_control:
        - { path: ^/in, roles: [ ROLE_ADMIN ] }
