services:
#    user.example:
#        class: cmh\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    security.access_denied.handler:
        class: UserBundle\Services\Security\AccessDeniedHandler